### ISSUE TITLE
Some issues to fix in the feature

### ISSUE THREAD

**Issue by anmarcu** [3DPrintDemon/Demon_Klipper_Essentials_Unified#1]
Hi, and thanks for doing all this work.
I think that I've spotted some things that can be improved:
1. CLEAN_NOZZLE is called in print start eve if is disabled in the config files. this is stopping you basically to use it unless you comment it out.
2. if you cancel your print, the offset is still there. would be nice to override the cancel print and reset the z offset.

**Comment by 3DPrintDemon** [comment]
Ahh you're quite correct I missed that one! I have updated the files now to only call NOZZLE_CLEAN if that variable is True. Appreciate you mentioning that one!

I've also added the Mainsail _CLIENT_VARIABLES to the demon_user_settings.cfg file along with a call for a macro that will raise the Z axis if its under Z 50, & if the printer is not printing it will remove the offset adjustment on a canceled print.
