### ISSUE TITLE
not a problem, but a question

### ISSUE THREAD

**Issue by igeighty** [3DPrintDemon/Demon_Klipper_Essentials_Unified#12]
Hi 3DPrintDemon,

I was wondering if you knew if anything in your scripts is telling the machine to extrude at 96%. I was chasing under extrusion problem and noticed in KlipperScreen under fin tuning that he extrusion was set at %96, I double checked slicer and its not telling it so I wondered if it was DKE playing a role.

again sorry to create a ticket, just something I can't work out myself. 
![IMG_8953](https://github.com/user-attachments/assets/b356dd40-e7b8-488f-a941-d708d3cb09c2)

**Comment by 3DPrintDemon** [comment]
There’s a very simple solution. Did you watch the setting’s tutorial video or look in the user settings files for filament settings? You’ll find the answer there.

**Comment by igeighty** [comment]
thankyou :)
