### ISSUE TITLE
How to add other filaments like PC or PA ?

### ISSUE THREAD

**Issue by emahpour** [3DPrintDemon/Demon_Klipper_Essentials_Unified#15]
Currently when I select other unsupported filaments in Orca it crashes as it only support those few base types. How can we add new filament support ?

**Comment by 3DPrintDemon** [comment]
Hi crashes of Orca slicer unfortunately has nothing to do with this macro pack. I suggest posting the issue of your Orca slicer crashing on the Orca slicer GitHub page.
