### ISSUE TITLE
adding custom code to "Change extrusion role G-code" breaks Orca Flow Calibration

### ISSUE THREAD

**Issue by emahpour** [3DPrintDemon/Demon_Klipper_Essentials_Unified#17]
After adding the following line to the "Change extrusion role G-code", it prevents Orca Flow Rate Calibration Pass1 from slicing the plate

```
_ADAPTIVE_PA TYPE=[extrusion_role]
```

Not sure if you have seen this. Do you suggest any other Calibration methods for Flow Rate that works with Demon customizations?

**Comment by 3DPrintDemon** [comment]
Hi there, thanks for the heads-up, apprentice it! 
I think this could be an issue with your build or version of Orca Slicer. Having that information being passed to the APA macro should not be an issue tbh. 

As you can see from the image below my copy of Orca works perfectly well with that `extrusion_role` info being passed there. This image shows a cleanly sliced Flow Pass1 plate.

This might be better suited as an issue on the Orca Slicer Github. Hopefully someone there might know the cause & you can get this resolved. In the meantime you can remove that line from your slicer & set the below option to false in the `demon_user_settings.cfg` file for the duration of your flow testing.

```
variable_orca_enable: False
```

As for any other flow rate tests. I either use the Orca Flow test or  I normally simply adjust on the fly while printing, so I wouldn't feel right recommending something that I've not used.

![Orca Flow pass1](https://github.com/user-attachments/assets/863c7659-5e40-4bc3-adda-b10e90715294)
