### ISSUE TITLE
AP -Test

### ISSUE THREAD

**Issue by Mad-Virus** [3DPrintDemon/Demon_Klipper_Essentials_Unified#21]
Throws an Error in Console.

18:05
Malformed command 'SET_DISPLAY_TEXT MSG="The pressure_advance value can then be calculated as pressure_advance =  +  * . (For example, 0 + 12.90 * .005 would be .258.)"'
18:05
Malformed command 'SET_DISPLAY_TEXT MSG="The pressure_advance value can then be calculated as pressure_advance =  +  * . (For example, 0 + 12.90 * .005 would be .258.)"'

**Comment by 3DPrintDemon** [comment]
Updated, the *'s were the problem.
