### ISSUE TITLE
Eddy   BED_MESH_CALIBRATE METHOD

### ISSUE THREAD

**Issue by aquari86** [3DPrintDemon/Demon_Klipper_Essentials_Unified#24]
I have a question about the bed mesh macro, I use the Btt eddy, I installed it and it works great, but how can I modify the macro so that this command "BED_MESH_CALIBRATE METHOD=rapid_scan ADAPTIVE=1 " is used, do you have an idea, thanks for your effort

**Comment by 3DPrintDemon** [comment]
Hi there! Full Eddy support will be coming in the next update of my macros. however in the meantime you go into the mesh builder file & search... 
```
ctrl+f
```
the search for each of these...
```
BED_MESH_CALIBRATE PROFILE=TPU
BED_MESH_CALIBRATE PROFILE=default
BED_MESH_CALIBRATE PROFILE=PETG
BED_MESH_CALIBRATE PROFILE=ASA
BED_MESH_CALIBRATE PROFILE=ABS

```
Then in replace each one with the corresponding entry here...
```
BED_MESH_CALIBRATE PROFILE=TPU METHOD=rapid_scan
BED_MESH_CALIBRATE PROFILE=default METHOD=rapid_scan
BED_MESH_CALIBRATE PROFILE=PETG METHOD=rapid_scan
BED_MESH_CALIBRATE PROFILE=ASA METHOD=rapid_scan
BED_MESH_CALIBRATE PROFILE=ABS METHOD=rapid_scan
```
We leave off the ADAPTIVE part of the command as we want to mesh the whole bed in this instance.
That should do the trick. I'll be testing Eddy on my systems this week so please let me know how it goes.

**Comment by aquari86** [comment]
yes, before you wrote it, I tried it and it worked straight away, thanks for your help

**Comment by 3DPrintDemon** [comment]
You're most welcome! happy printing!
