### ISSUE TITLE
BTT EDYY

### ISSUE THREAD

**Issue by ahmedbebars** [3DPrintDemon/Demon_Klipper_Essentials_Unified#25]
Is it possible to run BTT-EDDY

**Comment by 3DPrintDemon** [comment]
Hi! Full & automatic Eddy probe integration is coming in a few days with the v2.9 version update!

just doing some testing etc now!  Keep an eye out, you won’t want to miss it! 😉👍

**Comment by ahmedbebars** [comment]
Thank you for your interest and quick response.

**Comment by ahmedbebars** [comment]
Thanks for the update 

There are some problems when starting printing, as shown in the pictures
![1](https://github.com/user-attachments/assets/21921496-287e-44f4-8950-363ead07c083)
![2](https://github.com/user-attachments/assets/ebfe1565-1650-40df-a970-9fc629a64bd3)

**Comment by 3DPrintDemon** [comment]
Hi looks like you haven't install the timers correctly as that is the _HEAT_WAIT command. The SET_PIN command could well be related to that.

Please install the heat_wait timers here:
https://github.com/3DPrintDemon/Demon_Klipper_Essentials_Unified/blob/main/Documentation/Prerequisites/Prerequisites.md
