### ISSUE TITLE
//Unknown command:"_DRIVER_DEFINER"

### ISSUE THREAD

**Issue by patofoto** [3DPrintDemon/Demon_Klipper_Essentials_Unified#26]
Have placed the _DRIVER_DEFINER line following your instructions. Have a Klicky Probe. Getting this message but printer homes properly.

![IMG_8084](https://github.com/user-attachments/assets/3aabacf2-87ae-41a0-ba14-4be022c4431f)

<img width="961" alt="Screenshot 2024-09-30 at 10 01 57 AM" src="https://github.com/user-attachments/assets/0fbc8be4-b1cf-429e-b0dc-abbff06335d2">

Did I miss something?

**Comment by 3DPrintDemon** [comment]
so sorry, typo

change to 
```
_DRIVER_DEFINER
```

**Comment by 3DPrintDemon** [comment]
now corrected in documentation

**Comment by patofoto** [comment]
Awesome. I should have spotted this. Duh. Thanks.

**Comment by 3DPrintDemon** [comment]
Thats ok me too! it was my mistake as was in the documentation. What happens when you write macro instructions past your bed time! hahaha
