### ISSUE TITLE
need help with the macros

### ISSUE THREAD

**Issue by NickDK1** [3DPrintDemon/Demon_Klipper_Essentials_Unified#3]
how does one change the heatsoak time on the sv08 nothing changes if i change the 300 in the sovol sv08 heatsoak cfg.
and how does one make the printer go in the far left courner when its finished printing amd print gets canceled like stock sv08

**Comment by seenit783** [comment]
i was able to get the heatsoak macro kind of working but it was something i
found on internet. it kinda worked... had some issues.

**Comment by NickDK1** [comment]
no matter what i change the value too when printing it does a 10m heatsoak

**Comment by 3DPrintDemon** [comment]
Hi you should not edit the macro files. All adjustments must be made in deomon_user_settings.cfg file, if you edit the macro files themselves you risk breaking functionally or worse, your printer.  

To change the heat soak timers you must edit the low & high temperature chamber timer variables in the demon_user_settings.cfg file. 

It’s down past half way after all the filament settings. 

Please watch the posted video on the main page for more info on this & other settings.

**Comment by 3DPrintDemon** [comment]
This may help. 
![IMG_5855](https://github.com/user-attachments/assets/d86a65cc-021c-4eba-8fab-cbcd8acd6e7a)

**Comment by seenit783** [comment]
Oh I got however long I wanted but weird issues outside of heatsoak. Can't
remember. I'm on mainline klipper with pi4 and octopus pro amd haven't
tried that macro yet.

**Comment by 3DPrintDemon** [comment]
Im on the same basically, Voron 2.4 & the SV08 on BTT mainboard & Rpi4. No weird issues here. What were you experiencing exactly?

**Comment by NickDK1** [comment]
no kamp
when printing it wasnt live adjudsting z after the height map
and super slowdown where it was suddently only was running 3mm/s

so i have gone bk to standard 
im apparently not able to set this up correctly

**Comment by 3DPrintDemon** [comment]
> no kamp when printing it wasnt live adjudsting z after the height map and super slowdown where it was suddently only was running 3mm/s
> 
> so i have gone bk to standard im apparently not able to set this up correctly

Are you on a version of Klipper where their Adaptive Mesh is implemented?
Also have you activated `variable_adaptive_meshing: True` in the `demon_user_settings.cfg` file & followed the correct procure required for that system to work?

In the `Moonraker.conf` file, be sure the section below is present.
```
[file_manager]
enable_object_processing: True
```

Then activate `Label Objects` in your slicer?

TBH I have no idea why the actual print would slow down suddenly. There are no macros in this pack that would suddenly slow the printer in the middle of the print. There is a feed rate setting but is called one time only at the very start & that would mean the print would be that speed for the entire print unless changed.
