### ISSUE TITLE
TMC2660 isn't supported?

### ISSUE THREAD

**Issue by danb35** [3DPrintDemon/Demon_Klipper_Essentials_Unified#36]
I've used these macros on a Voron 0.1 and a CR-10S Pro with good results, but having a little trouble with my BLV Cube, which uses a Duet 2 motherboard.  I'm getting an error when I try to home that says `DRIVER_DEFINER: No supported URAT connected TMC Y axis driver detected` (and the same for X axis), which looks like it's a result of the tmc2660 not being listed in `demon_homing_control`.

Is there any reason I can't just add two sections like this to that file?
```
  {% if 'tmc2660 stepper_x' in printer.configfile.config %}
    SET_GCODE_VARIABLE MACRO=_DRIVER_VARS VARIABLE=run_x VALUE={printer.configfile.config['tmc2660 stepper_x'].run_current|float}
    {% if driver_vars.readback == True %}
      RESPOND TYPE=COMMAND MSG="Defined TMC2660 driver X axis"
    {% endif %}
```

**Comment by 3DPrintDemon** [comment]
Hi! that would be perfectly fine to do. I've just added the driver to the file in the main repo for you. Please download the latest `demon_homing_control` file.

**Comment by danb35** [comment]
That update did indeed resolve this.  Thanks!

**Comment by 3DPrintDemon** [comment]
Fantastic! Glad I could help you there. Happy printing!
