### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by patofoto** [3DPrintDemon/Demon_Klipper_Essentials_Unified#37]
Please forgive me if this is not the right place to post a question like this. I am wondering what is the most efficient, fool-proof way to update from version to version. 
I currently replace all files in the repo and use an application I have to compare text between two files to change the values of demon_user_settings_v2.9.1.cfg with my own personal values. 
Seems like a very manual endeavor. I know this is not "wrong" because things are working fine but is this the most efficient way?

**Comment by 3DPrintDemon** [comment]
Hi thats ok.
At the moment, yeah you need to transpose values manually. I'd ideally like to have some sort of script to automatically pull old settings over. This is something I've wanted to look into for some time.
For now if the file hasn't changed you can just use your old user settings file, or if there's only a couple of lines added you can paste them into your old file & update the version number if you're sure you got everything.
Hopefully I can get a better solution sorted out in the near future.
