### ISSUE TITLE
Incorrect [multi_pin fan_pins] on the SV08_EXTRA_INSTRUCTIONS.

### ISSUE THREAD

**Issue by TioSam13** [3DPrintDemon/Demon_Klipper_Essentials_Unified#45]
![baixados](https://github.com/user-attachments/assets/c5e008ad-09ed-49ea-98a2-49fedd5c0e02)

According to the image shown on:

https://github.com/Sovol3d/SV08/blob/main/Motherboard/Extra_PIN_definition.pdf

The pin definition on the SV08_EXTRA_INSTRUCTIONS.md is incorrect and leading to only the back fan work:

![Captura de tela 2024-11-01 224148](https://github.com/user-attachments/assets/290ed1c6-85ad-469c-ba30-486447f5c71d)

The correct pin would be: extra_mcu:PB0

![Captura de tela 2024-11-05 193005](https://github.com/user-attachments/assets/12c56653-a727-4ad4-a1bd-557c7b4c79c8)

Regards,

@3dswz on Instagram!

**Comment by 3DPrintDemon** [comment]
Hi thanks for your detailed post. I have a late production model SV08 & it has the fan plugged into the lower right port on the board which actually are the extra_mcu:PB1 pins. 

![IMG_7193](https://github.com/user-attachments/assets/6ceb018d-3783-47e0-8a74-fbb6e0f741a9)

The extra_mcu pin definitions image is wrong, as in the fact that it has two pins listed as PB0. 

Also the Sovol printer.cfg file posted on their SV08 repo lists the fan pins as I have them, extra_mcu:PA7 & extra_mcu:PB1

![IMG_7198](https://github.com/user-attachments/assets/4025ed00-3dce-43f3-9b11-e071dc7ff38c)

As you can see here the main parts cooling fan is working. 
![IMG_7194](https://github.com/user-attachments/assets/a0f3785c-b259-4319-9d04-c5609ab65ed2)
![IMG_7195](https://github.com/user-attachments/assets/0cc623f9-ca8e-4018-b6cd-62eaa339148a)

You can simply swap your main parts cooling fan over or, as you probably have done already, swap the pins in your printer.cfg to the pins your fan is plugged into.
