### ISSUE TITLE
LED issues

### ISSUE THREAD

**Issue by AndreasPlate** [3DPrintDemon/Demon_Klipper_Essentials_Unified#46]
Hi again,

sorry to bother you again, I'm not finding the right path to resolve this on my own and I feel like I've read everything 10 times by now.

After installing mainline klipper on my SV08, fully flashing the mcu and all the printer works. After installing the macro pack there is an error called "The value 'Screen_Colour' is not valid for LED".

I've tried to find out where it is called from or used in but I am not finding that specific output anywhere. I have two theories, either it is related to my HDMI screen colour or it is trying to set my LED light colour but I am uncertain which it is.

Any help would be apreciated :)

**Comment by 3DPrintDemon** [comment]
Hi the mainline install is really basic & for some reason does not include specific features present on the sv08 even though they’re in the stock printer.cfg by default. You have to add them. 

Klipper is telling you there that you haven’t got any LEDs named screen_colour, to get them you should add them in the displays section & board pins alias from the stock printer.cfg. 

This is an issue with mainline & the basic config set there.

**Comment by 3DPrintDemon** [comment]
Add these sections….

```

[board_pins]
aliases:
    # EXP1 header
    EXP1_1=PA8,   EXP1_2=PC9,
    EXP1_3=PA10,  EXP1_4=PA9,
    EXP1_5=PC11,  EXP1_6=PC10,
    EXP1_7=PD8,   EXP1_8=PC12,
    EXP1_9=<GND>, EXP1_10=<5V>,

    # EXP2 header
    EXP2_1=PB14,  EXP2_2=PB13,
    EXP2_3=PC7,   EXP2_4=PB12,
    EXP2_5=PC6,   EXP2_6=PB15,
    EXP2_7=PC8,   EXP2_8=<RST>,
    EXP2_9=<GND>, EXP2_10=<5V>

[display]                    
lcd_type: uc1701
cs_pin: EXP1_3
a0_pin: EXP1_4
rst_pin: EXP1_5
encoder_pins: ^EXP2_5, ^EXP2_3
click_pin: ^!EXP1_2
contrast: 63
spi_software_miso_pin: EXP2_1
spi_software_mosi_pin: EXP2_6
spi_software_sclk_pin: EXP2_2

[neopixel Screen_Colour]     
pin: EXP1_6
chain_count: 3
color_order: RGB             
initial_RED: 0.5             
initial_GREEN: 0.4           
initial_BLUE: 0.7  

```

**Comment by AndreasPlate** [comment]
Thank you, that did the trick! all seems to be running OK now. A note for mainline klipper people like me in the guide that you need the original printer.cfg in order to make it work might be a good idea.

Again thanks for the support!

**Comment by 3DPrintDemon** [comment]
Great that worked. 
That info is already published here in the repo for the sv08 click button screen menu system, but yes can add some info here also. 

https://github.com/3DPrintDemon/SV08/releases/tag/v1.0
