### ISSUE TITLE
Sovol SV08 START_PRINT vs PRINT_START

### ISSUE THREAD

**Issue by StefanKruk** [3DPrintDemon/Demon_Klipper_Essentials_Unified#50]
I have a Sovol SV08 and installed the Demon Klipper Essentials, Afterwards I printed the 12min Benchy on it.
In the Console a Message was displayed:

> Unknown command:"START_PRINT"

After investigation the Sovol SV08 has the Start Macro "START_PRINT" while the Demon Klipper Essentials has the macro "PRINT_START"
As stated in https://github.com/3DPrintDemon/Demon_Klipper_Essentials_Unified/blob/main/Documentation/INSTALL_INSTRUCTIONS/Sovol_SV08_Setup/SV08_EXTRA_INSTRUCTIONS.md

I disabled the `Macro.cfg`  with `# [include Macro.cfg]` which leads to the current Error Message.

Is there a reason why the Demon Klipper Essentials are specifying `PRINT_START` instead of `START_PRINT` ?
Would it not be better to have an alias so that `START_PRINT` will be calling `PRINT_START`  to also let the pre-sliced files from Sovol be printed without problems?

The same is with `END_PRINT` in original and `PRINT_END` in Demon Klipper Essential

**Comment by 3DPrintDemon** [comment]
The macros are not designed to print presliced files from any source, they rely on specific parameters being supplied to the macros from the slicer that are embedded in the sliced file. Hence the custom Gcode lines. 
It’s name is different for this reason, no correct name & no correct parameters results in it not being called so not to cause malfunctions & endless errors, instead nothing happens & you get one error only.
