### ISSUE TITLE
MACHINE_DEFINE option  is missing in demon_user_settings_v2.8.cfg

### ISSUE THREAD

**Issue by FoldZero** [3DPrintDemon/Demon_Klipper_Essentials_Unified#6]
`demon_user_settings_v2.8.cfg LINE100` & `demon_instructions_v1.3.txt LINE 371`
MACHINE_DEFINE option  is referenced but is missing in demon_user_settings_v2.8.cfg
EDIT - Just watched your video - MACHINE_DEFINE  is automated I see.

Pressing QGL before home does nothing and reports "You must Home First" . Can this be combined into QGL?
```
21:14
Must home axis first: 0.000 0.000 10.000 [0.000]
21:14
QUAD_GANTRY_LEVEL
```

`Auto bed Mesh Builder ` 
can we choose to enable or not selective filament types - i will never print ASA or ABS, 
eg
```
## PLA VARIABLES #######################
**enable_this_bed_PLA: False**
variable_pla_flow_rate: 96                       # Tune your flow rate for layers under 0.25mm
variable_pla_hi_flow_rate: 98  
```

`demon_instructions_v1.3.txt LINE 221`
Klipperscreen.conf  does not exists on ver 2.3.3 of SV08 Firmware
advice to create it ain /config folder may be needed for others

**Comment by 3DPrintDemon** [comment]
Awesome! Thank you for your contribution, I appreciate it, I'll get onto these ASAP!

Although the MACHINE_LEVEL_HOT/COLD macros should home the printer if its not currently active.

**Comment by FoldZero** [comment]
if your interested ( i haven't used git much) but I've attempted to make the changes for my own version
This [branch is [3 commits ahead of]  ](https://github.com/FoldZero/Demon_Klipper_2.8_Dev/compare/3DPrintDemon%3ADemon_Klipper_Essentials_Unified%3Amain...main )contains the changes

also i couldnt find the [gcode_macro _HEAT_WAIT] anywhere, im stumped. its used in the bed leveling if there isnt a sensor.

**Comment by 3DPrintDemon** [comment]
Hi sorry for the delay in replying. I'll take a look your folk & will modify things here as building options for filaments would be a good thing I think!

The HEAT_WAIT macro is located in my fork of these macros which should be included.
https://github.com/3DPrintDemon/Non_Blocking_Wait/releases/tag/Heat_Soak_Timers_V1.0

As per the file instructions. You're probably right, they are still in there from older versions. So will be easy to strip those back. No point on having it all duplicated I guess.

I'll see what can be done about 0º temp settings.

**Comment by OoSTARTERoO** [comment]
I suggest that _HEAT_WAIT should be included in this Unified macro pack
It gets called, but not defined on any of the folder

**Comment by 3DPrintDemon** [comment]
> I suggest that _HEAT_WAIT should be included in this Unified macro pack It gets called, but not defined on any of the folder

Hi the _HEAT_WAIT macros are a forked repo & used under GPL licenseing so cannot be directly included in this pack, sorry. For any future reference if no folder location is specified for a file then it means it can go in your main config folder on your printer & simply directly included in the printer.cfg
