### ISSUE TITLE
Not an issue - Any chance of CoPrint Support being integrated

### ISSUE THREAD

**Issue by justindail311** [3DPrintDemon/Demon_Klipper_Essentials_Unified#65]
Any chance of CoPrint KCM Set Support being integrated? They for the most part only seem to have a few hardware specific macros for capabilities that might need adding in print start/end and parking.

**Comment by 3DPrintDemon** [comment]
Hi, unfortunately I’m not convinced by the coprint system at this time. If it proves itself a cost effective & popular system that yields good result then I can look into it.
