### ISSUE TITLE
BED_MESH_CALIBRATE

### ISSUE THREAD

**Issue by Torbinator** [3DPrintDemon/Demon_Klipper_Essentials_Unified#67]
Hi, first of all, thank you for the great work.
I was wondering if it is possible to change the probe_count while using BED_MESH_CALIBRATE. I couldn't find anything, and the default probe_count defined in the bed_mesh section of my printer.cfg doesn't seem to be used during calibration.

**Comment by 3DPrintDemon** [comment]
Hi there, you’re most welcome. 
unfortunately the macros do not make any modifications or place any limits on system based behaviours like probing counts during mesh building or homing.
If you’re unable to change the number of points on a meshed grid it would point to an issue elsewhere, like possibly a duplicate section somewhere in the system. 
The probe_count (number of points in the mesh) is directly controlled by Klipper itself, when using bed_mesh_calibrate the macros simply tell Klipper that you want to build a mesh & what it should call it. Klipper does the rest of the work & builds a mesh to the specified grid that you chose in probe_count setting in the printer.cfg, so like 5,5 or 9,9 or 25,25 for example. The macros have no control over that in any way.
