### ISSUE TITLE
start/end macro cfg

### ISSUE THREAD

**Issue by Rez103** [3DPrintDemon/Demon_Klipper_Essentials_Unified#7]
just to bring to your attention, in the end print macro, line 520, “nevermore” caused and error on my setup., Where my Nevermore is configured as “Nevermore” in my printer.cfg and your start macro has “Nevermore” as well. Simple fix, but took me a couple prints to figure out.

**Comment by 3DPrintDemon** [comment]
ohhh nice catch! Thanks for the contribution! I've updated the file with the correction. Appreciate it.
