### ISSUE TITLE
PID tune error

### ISSUE THREAD

**Issue by mmrrxx00** [3DPrintDemon/Demon_Klipper_Essentials_Unified#76]
I updated everything this morning and when I try to run PID tune on the nozzle I get this error. 

Error evaluating 'gcode_macro PID_Tune_Mode:gcode': jinja2.exceptions.UndefinedError: 'ceal' is undefined

**Comment by 3DPrintDemon** [comment]
Hi! Well spotted! That one slipped by! Just fixed it, please run your mainsail update manager & it should bring down the amended file for you.

**Comment by mmrrxx00** [comment]
Seems to be fixed now Thank you so much

**Comment by 3DPrintDemon** [comment]
you're welcome!
