### ISSUE TITLE
Random Cleaning Nozzle Error

### ISSUE THREAD

**Issue by Tofusang** [3DPrintDemon/Demon_Klipper_Essentials_Unified#84]
Voron2.4 R2 300 brush&purge bucket on rear left hand rail.
When I hit Clean Nozzle, i got this error msg:
![image](https://github.com/user-attachments/assets/b69221da-638a-4489-ad72-55f748ec6908)

Error evaluating 'gcode_macro _step_control:gcode': jinja2.exceptions.UndefinedError: No random item, sequence was empty.
I have to turn off below section to use linear cleaning to make things happen
![image](https://github.com/user-attachments/assets/f7b735e5-cb72-4f46-a628-9788ca6bd883)
Any thing that I missed to be able to use the random cleaning function?
Attached is my user setting . 

[demon_user_settings_cleaner_variables_v1.1.0.txt](https://github.com/user-attachments/files/18267885/demon_user_settings_cleaner_variables_v1.1.0.txt)
[demon_user_settings_v2.9.4.txt](https://github.com/user-attachments/files/18267887/demon_user_settings_v2.9.4.txt)

**Comment by 3DPrintDemon** [comment]
Hi there, I just had a quick look & the only issue I can see immediately in your file is that you have the min/max X cleaning values reversed in the `demon_user_settings_cleaner_variables_v1.1.0.cfg`
```
YOUR VALUES...
variable_clean_min_x: 126
variable_clean_max_x: 88 
```
The minimum is the lower number on the axis & max is the higher. The cleaning should start at your... 

```
variable_start_x: 126 
```
then move to random points within the corrected range below.

```
CORRECTED VALUES...
variable_clean_min_x: 88
variable_clean_max_x: 126 
```

Obviously please increase you're cleaning Z height to say 10-15mm to test.

**Comment by Tofusang** [comment]
Thanks mate! This definitely will do. Great work on this project!

**Comment by 3DPrintDemon** [comment]
You're most welcome! Im glad you're enjoying my work.
